# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 16:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_auto_20180624_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulermodel',
            name='interval',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
