# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20180621_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Title', 'verbose_name_plural': 'Titles'},
        ),
    ]
