# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 14:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0007_schedulermodel_taskpatternmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulermodel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedulermodel',
            name='task_pattern',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.TaskPatternModel'),
        ),
    ]
