# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 18:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0010_auto_20180623_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subscribers',
            field=models.ManyToManyField(default=None, related_name='can_edit', to=settings.AUTH_USER_MODEL),
        ),
    ]
